default:
  http_metas:
    content-type: text/html



  stylesheets:    []

  javascripts:    []

  has_layout: off
  
defEditSuccess:
  has_layout: off
  javascripts:    [edit]
  stylesheets:    [layout]
  
widgetPageSuccess:
  has_layout: off
  javascripts:    [widget]
  stylesheets:    [widget]

cwSuccess:
  has_layout: off
  javascripts:    [widget]
  stylesheets:    [widget]

  